### ISSUE TITLE
Problems w/ App

### ISSUE THREAD

**Issue by triggertact** [rayzurbock/SmartThings-BigTalker#10] opened 2015-07-27 21:08 UTC
Hi, I'd really love to get this working correctly but am having numerous issues. Mainly just trying to get a contact sensor to trigger a spoken message, as well as a motion sensor to trigger a spoken message on my Sonos speakers. I actually just stumbled across this app recently after having tried the other app under SmartThings Labs many times without much success.

Anyways, I guess there are two or three main issues:

1) Setting a contact sensor to trigger a spoken message through Sonos worked most of the time when I first set it up, but then after a few hours it ceased speaking the verbal message and instead began playing about 10 seconds of a random song (as if playing music from the Sonos app).

2) Setting a different contact sensor to trigger a separate spoken message through a separate Sonos does not work at all, nor does it play music when triggered.

3) Setting a motion sensor to trigger a spoken message through the same Sonos speaker used in scenario # 2 also does not work at all.

Any thoughts??

Thanks,

Brandon

**Comment by alexruffell** [comment] 2015-10-09 23:37
@triggertact - I have the same issues but I believe it is a SmartThings issue and not BigTalker's. Try to reboot your hub to see if it starts working again but I am afraid it will stop again after some random time...

**Comment by rayzurbock** [comment] 2015-10-25 19:59
This is likely the problem: https://community.smartthings.com/t/smartthings-text-to-speech-for-sonos-playtext-not-working/20142

It looks like SmartThings backend method for converting text to speech in an mp3 audio file and sending that to your hub/device was broken somewhere around Aug 5, 2015.

Can anyone confirm if this is working properly now?

**Comment by rayzurbock** [comment] 2015-10-25 20:02
I just updated the code with release 1.1.1 which corrected an issue that would break BigTalker if a user configured a custom time restriction for Motion 1.

**Comment by rayzurbock** [comment] 2015-10-26 18:49
Perhaps this is resolved in version 1.1.3 released today?  Can you load the new code and see?  
You can also enable debug logging in the Big Talker settings (Big Talker > Configure Defaults > Enable debug logging), then login at graph.api.smartthings.com click Live Logging, cause actions that should cause Big Talker to talk, then click Big Talker in the Live Logging and send those for review if you like.  You can also click on your Sonos device in SmartThings Live Logging, copy and send those from the same time-frame as well.  There are also logs that can be extracted from your Sonos, but I do not have one so I cannot give you the steps involved with that.

**Change Logs from 1.1.1:**
 * 10/25/2015 - 1.1.1
    * BugFix: Corrected issue with Motion 1 announcement custom time restrictions
  * 10/25/2015 - 1.1.2
    * BugFix: Corrected issue with setting speech volume. Ensure that Volume is not 0; Set to 75 if it is.
  * 10/26/2015 - 1.1.3
    * BugFix: Added additional check in Talk() if using MusicPlayer device, currentTrack = null and currentStatus was "playing" then BT would not "resume", but instead would stop the track, PlayText() and not resume the track.
    * BugFix: Replaced deprecated "refreshAfterSelection" in dynamic pages with replacement "submitOnChange". This fixes things like TalkNow's expected operation.
    * Feature Enhancement: Additional logging added in Talk()

I am currently seeing an inconsistent issue where speech sometimes does not occur.  An error is posted in the device type logs (ie: Sonos, VLC-Thing, etc) for your device and stops the textToSpeech translation from occurring.  It will later work and then even later not.  This seems to be an issue with the SmartThings platform.  I have submitted SmartThings Support Request 150184 regarding this.  You can read up on this issue here if you like:  https://community.smartthings.com/t/vlc-thing-a-poor-mans-sonos/5433/190

**Comment by triggertact** [comment] 2015-10-26 22:45
Hi @rayzurbock, I'll try it out as soon as I can and report back. Thanks!

**Comment by alexruffell** [comment] 2015-10-28 14:23
Hi @rayzurbock , I updated to version 1.1.3 and I am not sure the motion issue was fixed. I had a motion sensor on the stairs that was supposed to say "Mind the steps" (as a test) when motion was detected and "Thank you" when motion was no longer detected. All I was getting was "thank you" but I never heard the "Mind the steps" message. I am currently getting other messages stating whether the front door is locked or not so the Sonos integration seems to be working.

**Comment by rayzurbock** [comment] 2015-10-28 18:03
@alexruffell  I have configured Motion group 1 to speak on active/inactive changes and tested here.  I am seeing in SmartThings LiveLogging, that the motion events are triggering speaking, but then I am getting an error back from SmartThings platform when it is supposed to convert the text phrase to audio prior to sending it to your device.  This is an ongoing issue with the platform in regards to processing of their supplied `textToSpeech()` function that they will have to resolve.  I have a new support case (150184) with them regarding this issue, but the issue has existed for several months now.  There have been various reports that only previously spoken phrases would work (cached). Supposedly they fixed it, but I am still seeing these issues.  I've seen it work on a certain phrase one minute and not the next and then work again later.  When it doesn't work the SmartThings Live Logging page will show this error for the device: `error java.lang.reflect.UndeclaredThrowableException`

Here are the logs that I have from my test (read from the bottom to the top)

    **ST: Device logs (VLCThing, My speech device. This would be your Sonos):**
    12:39:56 PM: error java.lang.reflect.UndeclaredThrowableException @ line 585
    12:39:55 PM: trace Executing: textToSpeech(Dining Room Motion is now inactive,true)
    12:39:55 PM: trace playTextAndResume(Dining Room Motion is now inactive, 95)
    12:39:56 PM: error java.lang.reflect.UndeclaredThrowableException @ line 585
    12:39:55 PM: trace Executing: textToSpeech(Dining Room Motion is now inactive,true)
    12:39:55 PM: trace playTextAndResume(Dining Room Motion is now inactive, 95)

    **ST: BigTalker logs:**
    12:39:56 PM: trace BIGTALKER(1.1.3) || VLCThing-Dining | Resuming play. Sending playText().
    12:39:56 PM: trace BIGTALKER(1.1.3) || mP | VLCThing-Dining | (4)Current Status: stopped.
    12:39:56 PM: debug BIGTALKER(1.1.3) || VLCThing-Dining | Volume: 50, Desired Volume: 95
    12:39:55 PM: trace BIGTALKER(1.1.3) || VLCThing-Office | Resuming play. Sending playTextAndResume().
    12:39:55 PM: trace BIGTALKER(1.1.3) || mP | VLCThing-Office | (4)Current Status: playing.
    12:39:55 PM: debug BIGTALKER(1.1.3) || VLCThing-Office | Volume: 91, Desired Volume: 95
    12:39:55 PM: trace BIGTALKER(1.1.3) || TALK(motion) >> Dining Room Motion is now inactive
    12:39:55 PM: debug BIGTALKER(1.1.3) || (onMotionEvent): motion, 1, inactive

Additional resources/discussions regarding this issue:
* https://community.smartthings.com/t/vlc-thing-a-poor-mans-sonos/5433/190
* https://community.smartthings.com/t/samsung-multiroom-m-series-speakers/26516/16
* https://community.smartthings.com/t/sonos-talking-alarm-clock/16971/60
* https://community.smartthings.com/t/door-left-open-with-photo-burst-hello-home-speech-version-1-3-5/6738/8
There are tons more if you search community.smartthings.com for "java.lang.reflect.UndeclaredThrowableException"

Sorry, I wish I could resolve this, but SmartThings will have to fix their backend before it will work consistently again.

**Comment by rayzurbock** [comment] 2015-11-12 04:04
I believe this issue is resolved as far as I am able to resolve it.  SmartThings is still having issues with the textToSpeech() function in their platform.  This seems to affect only new phrases that have never been spoken.  Occasionally a new phrase will work.  Once a phrase has been spoken, SmartThings caches the audio file on their servers for use next time without having to actually convert the text to an audible speech file.  As a workaround, I implemented a new function in 1.1.4-Beta1 (and up) to send a notification  to your device(s) running the SmartThings App when BigTalker is unable to successfully speak a desired phrase.  Find it here:  https://github.com/rayzurbock/SmartThings-BigTalker/tree/1.1.4-Beta

If you have an issue with speaking on events using BigTalker, please try changing your phrase for testing to something likely cached already on SmartThings servers, such as "Test", "Testing 1 2 3", "Testing", "Front Door Open", "Hello World"  (Without the quotes; I've tested these specific phrases and they all work for me).

Since this is a SmartThings platform issue and not a bug within BigTalker, I am going to go ahead and mark this issue as resolved.  Once SmartThings resolves the issues with the textToSpeech() function, BigTalker should be able to speak the desired, non-cached, phrases again.

**Closed by rayzurbock** 2015-11-12 04:04 UTC
